# Processamento de Linguagem Natural

In [1]:
import pandas as pd

df = pd.DataFrame({
    'text': [
      'Eu gosto de assistir jogos de futebol',
      'Já eu, prefiro assistir jogos de basquete'
    ]
    })

df.head()

                                        text
0      Eu gosto de assistir jogos de futebol
1  Já eu, prefiro assistir jogos de basquete

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(1,1))
vect.fit(df.text)
text_vect = vect.transform(df.text)

print(pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out()).T.to_string())

          0  1
assistir  1  1
basquete  0  1
de        2  1
eu        1  1
futebol   1  0
gosto     1  0
jogos     1  1
já        0  1
prefiro   0  1

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(2,2))
vect.fit(df.text)
text_vect = vect.transform(df.text)

print(pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out()).T.to_string())

                  0  1
assistir jogos    1  1
de assistir       1  0
de basquete       0  1
de futebol        1  0
eu gosto          1  0
eu prefiro        0  1
gosto de          1  0
jogos de          1  1
já eu             0  1
prefiro assistir  0  1

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(3,3))
vect.fit(df.text)
text_vect = vect.transform(df.text)

print(pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out()).T.to_string())

                        0  1
assistir jogos de       1  1
de assistir jogos       1  0
eu gosto de             1  0
eu prefiro assistir     0  1
gosto de assistir       1  0
jogos de basquete       0  1
jogos de futebol        1  0
já eu prefiro           0  1
prefiro assistir jogos  0  1

## Tokenização

In [5]:
from nltk.tokenize import word_tokenize
exemplo = 'O futebol brasileiro é o melhor do mundo. Você concorda?'
words = word_tokenize(exemplo)
words

['O',
 'futebol',
 'brasileiro',
 'é',
 'o',
 'melhor',
 'do',
 'mundo',
 '.',
 'Você',
 'concorda',
 '?']

## Regex

In [6]:
import re
rex = re.compile('\w+') #qualquer caracter alfanumérico - compilado
bandas = 'Queen, Aerosmith & Beatles'
print (bandas, '->', rex.findall(bandas))
phone = "2004-959-559 # This is Phone Number"
num = re.sub('#.*$', "", phone) #elimina tudo após #
print ("Phone Num : ", num)
num = re.sub(r'\D', "", phone)# só deixa número
print ("Phone Num : ", num)

Queen, Aerosmith & Beatles -> ['Queen', 'Aerosmith', 'Beatles']
Phone Num :  2004-959-559
Phone Num :  2004959559

In [7]:
regex = r"(?<=@)[^.]+(?=\.)"
re.findall(regex, "batman@gmail.com")

['gmail']

In [8]:
s = "batman@gmail.com"
s.split("@")[1].split(".")[0]

'gmail'

## Stop-words

In [9]:
import nltk
nltk.download('stopwords')
nltk.corpus.stopwords.words('portuguese')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/dhenyfernandes/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['a',
 'à',
 'ao',
 'aos',
 'aquela',
 'aquelas',
 'aquele',
 'aqueles',
 'aquilo',
 'as',
 'às',
 'até',
 'com',
 'como',
 'da',
 'das',
 'de',
 'dela',
 'delas',
 'dele',
 'deles',
 'depois',
 'do',
 'dos',
 'e',
 'é',
 'ela',
 'elas',
 'ele',
 'eles',
 'em',
 'entre',
 'era',
 'eram',
 'éramos',
 'essa',
 'essas',
 'esse',
 'esses',
 'esta',
 'está',
 'estamos',
 'estão',
 'estar',
 'estas',
 'estava',
 'estavam',
 'estávamos',
 'este',
 'esteja',
 'estejam',
 'estejamos',
 'estes',
 'esteve',
 'estive',
 'estivemos',
 'estiver',
 'estivera',
 'estiveram',
 'estivéramos',
 'estiverem',
 'estivermos',
 'estivesse',
 'estivessem',
 'estivéssemos',
 'estou',
 'eu',
 'foi',
 'fomos',
 'for',
 'fora',
 'foram',
 'fôramos',
 'forem',
 'formos',
 'fosse',
 'fossem',
 'fôssemos',
 'fui',
 'há',
 'haja',
 'hajam',
 'hajamos',
 'hão',
 'havemos',
 'haver',
 'hei',
 'houve',
 'houvemos',
 'houver',
 'houvera',
 'houverá',
 'houveram',
 'houvéramos',
 'houverão',
 'houverei',
 'houverem',
 'houveremos',
 'houveria',
 'houveriam',
 'houveríamos',
 'houvermos',
 'houvesse',
 'houvessem',
 'houvéssemos',
 'isso',
 'isto',
 'já',
 'lhe',
 'lhes',
 'mais',
 'mas',
 'me',
 'mesmo',
 'meu',
 'meus',
 'minha',
 'minhas',
 'muito',
 'na',
 'não',
 'nas',
 'nem',
 'no',
 'nos',
 'nós',
 'nossa',
 'nossas',
 'nosso',
 'nossos',
 'num',
 'numa',
 'o',
 'os',
 'ou',
 'para',
 'pela',
 'pelas',
 'pelo',
 'pelos',
 'por',
 'qual',
 'quando',
 'que',
 'quem',
 'são',
 'se',
 'seja',
 'sejam',
 'sejamos',
 'sem',
 'ser',
 'será',
 'serão',
 'serei',
 'seremos',
 'seria',
 'seriam',
 'seríamos',
 'seu',
 'seus',
 'só',
 'somos',
 'sou',
 'sua',
 'suas',
 'também',
 'te',
 'tem',
 'tém',
 'temos',
 'tenha',
 'tenham',
 'tenhamos',
 'tenho',
 'terá',
 'terão',
 'terei',
 'teremos',
 'teria',
 'teriam',
 'teríamos',
 'teu',
 'teus',
 'teve',
 'tinha',
 'tinham',
 'tínhamos',
 'tive',
 'tivemos',
 'tiver',
 'tivera',
 'tiveram',
 'tivéramos',
 'tiverem',
 'tivermos',
 'tivesse',
 'tivessem',
 'tivéssemos',
 'tu',
 'tua',
 'tuas',
 'um',
 'uma',
 'você',
 'vocês',
 'vos']

## Normalização de Texto

In [10]:
ex1 = 'O carro que estava quebrado voltou a funcionar'
ex2 = 'Meu carro quebrou e não está funcionando'

print(word_tokenize(ex1))
print(word_tokenize(ex2))

['O', 'carro', 'que', 'estava', 'quebrado', 'voltou', 'a', 'funcionar']
['Meu', 'carro', 'quebrou', 'e', 'não', 'está', 'funcionando']

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

ex1 = 'O carro que estava quebrado voltou a funcionar'
ex2 = 'Meu carro quebrou e não está funcionando'

df = pd.DataFrame({'text':[ex1,ex2]})

vect = CountVectorizer(ngram_range=(1,1))
vect.fit(df.text)
text_vect = vect.transform(df.text)

print(pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out()).T.to_string())

             0  1
carro        1  1
estava       1  0
está         0  1
funcionando  0  1
funcionar    1  0
meu          0  1
não          0  1
que          1  0
quebrado     1  0
quebrou      0  1
voltou       1  0

In [12]:
text_vect.shape

(2, 11)

**Importante** notar que, intrinsicamente, CountVectorizer já realiza o processo de passar as palavras para minúscula. Acesse a documentação e veja [link](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)

## Stop-words

In [13]:
stops = nltk.corpus.stopwords.words('portuguese')

vect = CountVectorizer(ngram_range=(1,1), stop_words=stops)
vect.fit(df.text)
text_vect = vect.transform(df.text)

print(pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out()).T.to_string())

             0  1
carro        1  1
funcionando  0  1
funcionar    1  0
quebrado     1  0
quebrou      0  1
voltou       1  0

In [14]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
examples = [
   "go","going",
   "goes","gone","went"
]

wnl = WordNetLemmatizer()

for word in examples:
  print(wnl.lemmatize(word, 'v'))

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/dhenyfernandes/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

go
go
go
go
go

In [15]:
!pip install spacy
!python -m spacy download pt_core_news_sm

Requirement already satisfied: spacy in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (3.6.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (2.2.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (3.3.0)
Requirement already satisfied: jinja2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (3.1.2)
Requirement already satisfied: packaging>=20.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (22.0)
Requirement already satisfied: pathy>=0.10.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (0.10.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (2.32.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (2.0.9)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (0.9.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (3.0.8)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (1.1.2)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (5.2.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (4.66.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (1.0.9)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (1.0.4)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (2.0.7)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (2.4.7)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (8.1.12)
Requirement already satisfied: setuptools in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (65.6.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (3.0.12)
Requirement already satisfied: numpy>=1.15.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy) (1.23.5)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.5.0)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: pydantic-core==2.6.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.6.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.7.10)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.1.1)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from typer<0.10.0,>=0.3.0->spacy) (8.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from jinja2->spacy) (2.1.1)
Collecting pt-core-news-sm==3.6.0
  Using cached https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.6.0/pt_core_news_sm-3.6.0-py3-none-any.whl (13.0 MB)
Requirement already satisfied: spacy<3.7.0,>=3.6.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from pt-core-news-sm==3.6.0) (3.6.1)
Requirement already satisfied: jinja2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (3.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.4.7)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.2.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (3.3.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.0.9)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.32.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (3.0.12)
Requirement already satisfied: packaging>=20.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (22.0)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (8.1.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (1.1.2)
Requirement already satisfied: numpy>=1.15.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (1.23.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (1.0.9)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (4.66.5)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (3.0.8)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (5.2.1)
Requirement already satisfied: setuptools in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (65.6.3)
Requirement already satisfied: pathy>=0.10.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (0.10.2)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (1.0.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (0.9.0)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (0.5.0)
Requirement already satisfied: pydantic-core==2.6.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.6.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (4.12.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (1.26.14)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from thinc<8.2.0,>=8.1.8->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (0.7.10)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from thinc<8.2.0,>=8.1.8->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (0.1.1)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from typer<0.10.0,>=0.3.0->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (8.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/dhenyfernandes/anaconda3/lib/python3.10/site-packages (from jinja2->spacy<3.7.0,>=3.6.0->pt-core-news-sm==3.6.0) (2.1.1)
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')

In [16]:
import spacy
nlp = spacy.load('pt_core_news_sm')
doc = nlp(u'quebrou,quebraram,quebrado,quebrariam')
[token.lemma_ for token in doc if token.pos_ == 'VERB']

['quebrar', 'quebrar', 'quebrar', 'quebrar']

In [17]:
import nltk
from nltk.stem import PorterStemmer

examples = [
    "connection","connections",
    "connective","connecting","connected"
]

ps = PorterStemmer()

for word in examples:
  print(ps.stem(word))

connect
connect
connect
connect
connect

In [18]:
from nltk.stem import PorterStemmer

examples = ["conecta","conectado","conectamos","desconectados","conectividade"]

ps = PorterStemmer()

for word in examples:
  print(ps.stem(word))

conecta
conectado
conectamo
desconectado
conectividad

In [19]:
from nltk.stem.rslp import RSLPStemmer

examples = ["conecta","conectado","conectamos","desconectados","conectividade"]

rslp = RSLPStemmer()

for word in examples:
  print(rslp.stem(word))

conect
conect
conect
desconect
conect

In [20]:
stem1 = " ".join([rslp.stem(x) for x in word_tokenize(ex1)])
stem2 = " ".join([rslp.stem(x) for x in word_tokenize(ex2)])

In [21]:
df = pd.DataFrame({'text':[stem1,stem2]})
stops = nltk.corpus.stopwords.words('portuguese')

vect = CountVectorizer(ngram_range=(1,1), stop_words=stops)
vect.fit(df.text)
text_vect = vect.transform(df.text)

print(pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out()).T.to_string())

         0  1
carr     1  1
est      1  1
funcion  1  1
quebr    1  1
volt     1  0

## POS-Tagger

In [22]:
import nltk
import pandas as pd
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/dhenyfernandes/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/dhenyfernandes/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [23]:
text = nltk.word_tokenize("And now for something completely different")
nltk.pos_tag(text)

[('And', 'CC'),
 ('now', 'RB'),
 ('for', 'IN'),
 ('something', 'NN'),
 ('completely', 'RB'),
 ('different', 'JJ')]

In [24]:
text1 = nltk.word_tokenize("They refuse to permit us to obtain the refuse permit")
nltk.pos_tag(text1)

[('They', 'PRP'),
 ('refuse', 'VBP'),
 ('to', 'TO'),
 ('permit', 'VB'),
 ('us', 'PRP'),
 ('to', 'TO'),
 ('obtain', 'VB'),
 ('the', 'DT'),
 ('refuse', 'NN'),
 ('permit', 'NN')]

In [25]:
nltk.download('brown')
text = nltk.Text(word.lower() for word in nltk.corpus.brown.words())
text.similar('woman')

[nltk_data] Downloading package brown to
[nltk_data]     /Users/dhenyfernandes/nltk_data...
[nltk_data]   Package brown is already up-to-date!

man time day year car moment world house family child country boy
state job place way war girl work word

In [26]:
text.similar('bought')

made said done put had seen found given left heard was been brought
set got that took in told felt

In [27]:
text.similar('over')

in on to of and for with from at by that into as up out down through
is all about

In [28]:
text.similar('the')

a his this their its her an that our any all one these my in your no
some other and

In [29]:
nltk.download('floresta')
from nltk.corpus import floresta
floresta.tagged_words()

[nltk_data] Downloading package floresta to
[nltk_data]     /Users/dhenyfernandes/nltk_data...
[nltk_data]   Package floresta is already up-to-date!

[('Um', '>N+art'), ('revivalismo', 'H+n'), ...]

In [30]:
def simplify_tag(t):
  if "+" in t:
    return t.split("+")[1]
  return t 

twords = nltk.corpus.floresta.tagged_words()
twords = [(w.lower(),simplify_tag(t)) for (w,t) in twords]
twords[:10]

[('um', 'art'),
 ('revivalismo', 'n'),
 ('refrescante', 'adj'),
 ('o', 'art'),
 ('7_e_meio', 'prop'),
 ('é', 'v-fin'),
 ('um', 'art'),
 ('ex-libris', 'n'),
 ('de', 'prp'),
 ('a', 'art')]

In [31]:
print(nltk.corpus.floresta.readme())

Portuguese Treebank

Projecto Floresta Sinta(c)tica -- http://www.linguateca.pt/Floresta/
Version 7.4  Distributed with permission.

Penn Treebank format, available from http://linguateca.di.uminho.pt/FS/fs.html

Key to tags (http://visl.sdu.dk/visl/pt/portsymbol.html)

<ACC          direct object
<ACC-PASS     passive use of pronoun 'se'
<ADVS, <ADVO  adverbial argument
<ADVL         adjunct adverbial
<DAT          dative (indirect) object
<FOC          focus marker (or right focus bracket)
<OC           object complement
<PASS         agent of passive
<PIV          prepositional object
<PRED         free (subject) predicative, right of main verb
<SC           subject complement
<SUBJ         subject
>A            adverbial pre-adject (intensifier before adjective, adverb, pronoun or participle)
>N            prenominal modifier
>P            modifier of prepositional phrase (intensifier, operator or focus adverb)
>S            modifier of clause (intensifier, operator or focus adverb)
A<            adverbial post-adject (modifier or argument of adjective, adverb or participle)
A<ADV         adverbial argument of attributive participle
A<ADVL        adverbial adjunct of attributive participle
A<PASS        agent of passive after attributive participle
A<PIV         prepositional object of attributive participle
A<SC          subject complement of attributive participle
ACC>          accusative (direct) object
ACC>-PASS     passive use of pronoun 'se'
ACC>>         double-fronted accusative (direct) object before matrix verb
ADVS>, ADVO>  adverbial argument
ADVL          top node adverbial
ADVL>         adjunct adverbial
ADVL>A        adjunct adverbial before attributive participle
ADVL>AS<      adjunct adverbial in averbal clause
APP           identifying apposition
AS<           clause body of averbal clause
CO            co-ordinator
COM           comparator (heading averbal clause)
DAT>          dative (intransitive) object
FAUX          finite auxiliary
FMV           finite main verb
FOC>          focus marker (or left focus bracket)
IAUX          non-finite auxiliary
IMV           non-finite main verb
KOMP<         argument of comparative hook
N<            postnominal modifier or argument
N<PRED        postnominal (in-group) predicative (or non-identifying apposition)
NPHR          top node noun phrase
NUM<          second part of numeral chain
OC>           object complement
P<            argument of preposition
PIV>          prepositional object
PRD           predicator (heading averbal clause)
PRED>         free (subject) predicative, left of main verb
PREF          prefix (category being phased out)
PRT-AUX<      auxiliary particle
S<            statement predicative (sentence apposition)
SC>           subject complement
SUB           subordinator
SUBJ>         subject
SUBJ>>        double-fronted subject, with interfering matrix og quoting verb
TOP           topic constituent
VOK           vocative constituent

### Default Tagger

In [32]:
tags = [tag for (word, tag) in twords]
nltk.FreqDist(tags).max()

'n'

In [33]:
raw = 'Esse é um exemplo utilizando o marcador padrão'
tokens = nltk.word_tokenize(raw)
default_tagger = nltk.DefaultTagger('n')
default_tagger.tag(tokens)

[('Esse', 'n'),
 ('é', 'n'),
 ('um', 'n'),
 ('exemplo', 'n'),
 ('utilizando', 'n'),
 ('o', 'n'),
 ('marcador', 'n'),
 ('padrão', 'n')]

In [34]:
tsents = floresta.tagged_sents()
tsents = [[(w.lower(),simplify_tag(t)) for (w,t) in sent] for sent in tsents if sent]
train = tsents[1000:]
test = tsents[:1000]
tsents[1:3]

[[('o', 'art'),
  ('7_e_meio', 'prop'),
  ('é', 'v-fin'),
  ('um', 'art'),
  ('ex-libris', 'n'),
  ('de', 'prp'),
  ('a', 'art'),
  ('noite', 'n'),
  ('algarvia', 'adj'),
  ('.', '.')],
 [('é', 'v-fin'),
  ('uma', 'num'),
  ('de', 'prp'),
  ('as', 'art'),
  ('mais', 'adv'),
  ('antigas', 'adj'),
  ('discotecas', 'n'),
  ('de', 'prp'),
  ('o', 'art'),
  ('algarve', 'prop'),
  (',', ','),
  ('situada', 'v-pcp'),
  ('em', 'prp'),
  ('albufeira', 'prop'),
  (',', ','),
  ('que', 'pron-indp'),
  ('continua', 'v-fin'),
  ('a', 'prp'),
  ('manter', 'v-inf'),
  ('os', 'art'),
  ('traços', 'n'),
  ('decorativos', 'adj'),
  ('e', 'conj-c'),
  ('as', 'art'),
  ('clientelas', 'n'),
  ('de', 'prp'),
  ('sempre', 'adv'),
  ('.', '.')]]

In [35]:
tsents[1:3]

[[('o', 'art'),
  ('7_e_meio', 'prop'),
  ('é', 'v-fin'),
  ('um', 'art'),
  ('ex-libris', 'n'),
  ('de', 'prp'),
  ('a', 'art'),
  ('noite', 'n'),
  ('algarvia', 'adj'),
  ('.', '.')],
 [('é', 'v-fin'),
  ('uma', 'num'),
  ('de', 'prp'),
  ('as', 'art'),
  ('mais', 'adv'),
  ('antigas', 'adj'),
  ('discotecas', 'n'),
  ('de', 'prp'),
  ('o', 'art'),
  ('algarve', 'prop'),
  (',', ','),
  ('situada', 'v-pcp'),
  ('em', 'prp'),
  ('albufeira', 'prop'),
  (',', ','),
  ('que', 'pron-indp'),
  ('continua', 'v-fin'),
  ('a', 'prp'),
  ('manter', 'v-inf'),
  ('os', 'art'),
  ('traços', 'n'),
  ('decorativos', 'adj'),
  ('e', 'conj-c'),
  ('as', 'art'),
  ('clientelas', 'n'),
  ('de', 'prp'),
  ('sempre', 'adv'),
  ('.', '.')]]

In [36]:
tagger0 = nltk.DefaultTagger('n')
print(tagger0.evaluate(test))

0.17800040072129833

/var/folders/8r/76rtgv650dq8578qqnhrpvym0000gn/T/ipykernel_47524/1235642322.py:2: DeprecationWarning:
  Function evaluate() has been deprecated.  Use accuracy(gold)
  instead.
  print(tagger0.evaluate(test))

### Unigram Tagger

In [37]:
tagger1 = nltk.UnigramTagger(train)
print(tagger1.evaluate(test))

0.8522139851733119

/var/folders/8r/76rtgv650dq8578qqnhrpvym0000gn/T/ipykernel_47524/1679567981.py:2: DeprecationWarning:
  Function evaluate() has been deprecated.  Use accuracy(gold)
  instead.
  print(tagger1.evaluate(test))

### Bigram Tagger

In [38]:
tagger2 = nltk.BigramTagger(train)
print(tagger2.accuracy(test))

0.14626327389300742

### Combinação de Tagger

In [39]:
tagger1 = nltk.UnigramTagger(train, backoff=tagger0)
print('tagger1: ',tagger1.accuracy(test))
tagger2 = nltk.BigramTagger(train, backoff=tagger1)
print('tagger2: ',tagger2.accuracy(test))

tagger1:  0.8740532959326788
tagger2:  0.8900420757363254

### Salvando Tagger

In [40]:
from pickle import dump
output = open('tagger.pkl', 'wb')
dump(tagger2, output, -1)
output.close()

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

In [41]:
from pickle import load
input = open('tagger.pkl', 'rb')
tagger = load(input)
input.close()

In [42]:
text1 = "Isso é para você."
text2 = "para com isso"
tokens1 = text1.split()
tokens2 = text2.split()
print('text1: ',tagger.tag(tokens1))
print('text2: ',tagger.tag(tokens2))

text1:  [('Isso', 'n'), ('é', 'v-fin'), ('para', 'prp'), ('você.', 'n')]
text2:  [('para', 'prp'), ('com', 'prp'), ('isso', 'pron-indp')]

# Classificação de textos

Para entender melhor o problema de classificação de textos, vamos começar com um exemplo básico que servirá como intuição para nos aprofundarmos depois

In [43]:
import pandas as pd
import time
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# exemplo de documento e corpus
df_fiap = pd.DataFrame({
    'text': [
      'Sobre MBA? Eu gostei muito do MBA da FIAP',
      'O MBA da FIAP pode melhorar, não gostei muito',
      'Foi muito importante para meu desenvolvimento',
      'Poderia ser mais técnico. Não gostei'
    ],
    'class': [
      'positivo',
      'negativo',
      'positivo',
      'negativo'
    ]})

df_fiap.head()

                                            text     class
0      Sobre MBA? Eu gostei muito do MBA da FIAP  positivo
1  O MBA da FIAP pode melhorar, não gostei muito  negativo
2  Foi muito importante para meu desenvolvimento  positivo
3           Poderia ser mais técnico. Não gostei  negativo

Podemos vetorizar os dados e ver como fica o espaço de características nesse caso. Vamos usar a mesma solução que vimos aula passada:

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(1,1))
vect.fit(df_fiap.text)
text_vect = vect.transform(df_fiap.text)

pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out())

   da  desenvolvimento  do  eu  fiap  foi  gostei  importante  mais  mba  melhorar  meu  muito  não  para  pode  poderia  ser  sobre  técnico
0   1                0   1   1     1    0       1           0     0    2         0    0      1    0     0     0        0    0      1        0
1   1                0   0   0     1    0       1           0     0    1         1    0      1    1     0     1        0    0      0        0
2   0                1   0   0     0    1       0           1     0    0         0    1      1    0     1     0        0    0      0        0
3   0                0   0   0     0    0       1           0     1    0         0    0      0    1     0     0        1    1      0        1

Usando Bigrama

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(2,2))
vect.fit(df_fiap.text)
text_vect = vect.transform(df_fiap.text)

pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out())

   da fiap  do mba  eu gostei  fiap pode  foi muito  gostei muito  importante para  mais técnico  mba da  mba eu  melhorar não  meu desenvolvimento  muito do  muito importante  não gostei  para meu  pode melhorar  poderia ser  ser mais  sobre mba  técnico não
0        1       1          1          0          0             1                0             0       1       1             0                    0         1                 0           0         0              0            0         0          1            0
1        1       0          0          1          0             1                0             0       1       0             1                    0         0                 0           1         0              1            0         0          0            0
2        0       0          0          0          1             0                1             0       0       0             0                    1         0                 1           0         1              0            0         0          0            0
3        0       0          0          0          0             0                0             1       0       0             0                    0         0                 0           1         0              0            1         1          0            1

Usando Trigrama

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(3,3))
vect.fit(df_fiap.text)
text_vect = vect.transform(df_fiap.text)

pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out())

   da fiap pode  do mba da  eu gostei muito  fiap pode melhorar  foi muito importante  gostei muito do  importante para meu  mais técnico não  mba da fiap  mba eu gostei  melhorar não gostei  muito do mba  muito importante para  não gostei muito  para meu desenvolvimento  pode melhorar não  poderia ser mais  ser mais técnico  sobre mba eu  técnico não gostei
0             0          1                1                   0                     0                1                    0                 0            1              1                    0             1                      0                 0                         0                  0                 0                 0             1                   0
1             1          0                0                   1                     0                0                    0                 0            1              0                    1             0                      0                 1                         0                  1                 0                 0             0                   0
2             0          0                0                   0                     1                0                    1                 0            0              0                    0             0                      1                 0                         1                  0                 0                 0             0                   0
3             0          0                0                   0                     0                0                    0                 1            0              0                    0             0                      0                 0                         0                  0                 1                 1             0                   1

Podemos ver como fica a representação usando TFIDF. É interessante fazer uma comparação com a solução usando Unigram

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(ngram_range=(1,1), use_idf=True)
vect.fit(df_fiap.text)
text_vect = vect.transform(df_fiap.text)

pd.DataFrame(text_vect.A, columns=vect.get_feature_names_out())

         da  desenvolvimento        do        eu      fiap       foi    gostei  importante      mais       mba  melhorar       meu     muito       não      para      pode   poderia       ser     sobre   técnico
0  0.287039         0.000000  0.364073  0.364073  0.287039  0.000000  0.232383    0.000000  0.000000  0.574078  0.000000  0.000000  0.232383  0.000000  0.000000  0.000000  0.000000  0.000000  0.364073  0.000000
1  0.342426         0.000000  0.000000  0.000000  0.342426  0.000000  0.277223    0.000000  0.000000  0.342426  0.434323  0.000000  0.277223  0.342426  0.000000  0.434323  0.000000  0.000000  0.000000  0.000000
2  0.000000         0.430037  0.000000  0.000000  0.000000  0.430037  0.000000    0.430037  0.000000  0.000000  0.000000  0.430037  0.274487  0.000000  0.430037  0.000000  0.000000  0.000000  0.000000  0.000000
3  0.000000         0.000000  0.000000  0.000000  0.000000  0.000000  0.284626    0.000000  0.445922  0.000000  0.000000  0.000000  0.000000  0.351570  0.000000  0.000000  0.445922  0.445922  0.000000  0.445922

## Biblioteca para normalização de textos

Vimos várias maneiras de realizar o tratamento e normalização dos textos ao longo dessas duas aulas (e vou incluir mais algumas opções aqui). Por conta disso, é interessante construir uma classe que implementa todas essas funções. Isso facilita o reaproveitamento de código e permite você construir sua própria biblioteca de códigos

In [48]:
import nltk
import re
import string
import unicodedata

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
    
        
def normalize_accents(text):
    return unicodedata.normalize("NFKD", text).encode("ASCII", "ignore").decode("utf-8")

def normalize_str(text):
    text = text.lower()
    text = remove_punctuation(text)
    text = normalize_accents(text)
    text = re.sub(re.compile(r" +"), " ",text)
    return " ".join([w for w in text.split()])

def remove_punctuation(text):
    punctuations = string.punctuation
    table = str.maketrans({key: " " for key in punctuations})
    text = text.translate(table)
    return text


def tokenizer(text):
    stop_words = nltk.corpus.stopwords.words("english") # portuguese, caso o dataset seja em português
    if isinstance(text, str):
        text = normalize_str(text)
        text = "".join([w for w in text if not w.isdigit()])
        text = word_tokenize(text)
        text = [x for x in text if x not in stop_words]
        text = [y for y in text if len(y) > 2]
        return " ".join([t for t in text])
    else:
        return None

In [49]:
tokenizer("Exemplo$ de 12 normalização!!")

'exemplo normalizacao'

Vamos agora usar essas funções que criamos num dataset real e entender como realizar o pré-processamento de textos bem como preparar os dados para treinar um modelo de machine learning.

Para isso, vamos usar o dataset UCI News Aggregator, que pode ser consultado nesse [link](https://archive.ics.uci.edu/ml/datasets/News+Aggregator)

In [51]:
df = pd.read_csv('Bases/uci-news-aggregator.csv')
df = df[['TITLE','CATEGORY']]
#categories: b = business, t = science and technology, e = entertainment, m = health

In [52]:
# shuffle - embaralha as linhas para evitar problema (aprende apenas amostras de uma classe e isso pode levar o gradiente a
# ficar preso num mínimo local e só aprender bem sobre tal classe)
from sklearn.utils import shuffle
df = shuffle(df)
df = df.reset_index(drop = True)
df.head()

                                               TITLE CATEGORY
0  Joe Cada adds to bracelet collection at World ...        e
1  Arrest made in Devon in connection with Blacks...        t
2  'I was a kid': Justin Bieber apologizes for ra...        e
3   Snowden feels vindicated by proposed NSA reforms        t
4  Mariah Carey - Nick Cannon Sparks Controversy ...        e

In [53]:
df['Title_Treated'] = df['TITLE'].apply(tokenizer)

In [54]:
df.head()

                                               TITLE CATEGORY                                      Title_Treated
0  Joe Cada adds to bracelet collection at World ...        e  joe cada adds bracelet collection world series...
1  Arrest made in Devon in connection with Blacks...        t  arrest made devon connection blackshades softw...
2  'I was a kid': Justin Bieber apologizes for ra...        e           kid justin bieber apologizes racist joke
3   Snowden feels vindicated by proposed NSA reforms        t      snowden feels vindicated proposed nsa reforms
4  Mariah Carey - Nick Cannon Sparks Controversy ...        e  mariah carey nick cannon sparks controversy al...

Comparando amostras antes e depois do tratamento:

In [55]:
print('Antes: ', df['TITLE'][0], '\n')
print('Depois: ', df['Title_Treated'][0])

Antes:  Joe Cada adds to bracelet collection at World Series of Poker, looking for a third

Depois:  joe cada adds bracelet collection world series poker looking third

Criando features e Labels. A título de comparação com o modelo de representação Word2Vec que veremos na última aula, vamos usar apenas as primeiras 100k amostras e, a partir delas, criar conjunto de treino e teste.

In [56]:
from sklearn.model_selection import train_test_split
X = df['Title_Treated'].values
y = df['CATEGORY'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

Agora, precisamos transformar os dados para a representação numérica. Vamos usar o modelo BoW, que pode ser obtido usando CountVectorizer

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(lowercase=False) 
vect.fit(X_train)
X_train = vect.transform(X_train)
X_train

<295693x43779 sparse matrix of type '<class 'numpy.int64'>'
	with 1955385 stored elements in Compressed Sparse Row format>

In [58]:
X_test = vect.transform(X_test)
X_test

<126726x43779 sparse matrix of type '<class 'numpy.int64'>'
	with 831276 stored elements in Compressed Sparse Row format>

In [59]:
from sklearn import svm
clf = svm.SVC(kernel='linear') 
start_time = time.time()
clf.fit(X_train, y_train)
end_time = time.time()
print('tempo decorrido: ',end_time-start_time, 'segundos')
y_pred = clf.predict(X_test)

tempo decorrido:  3185.1564033031464 segundos

In [60]:
import datetime
sec = end_time-start_time
print(str(datetime.timedelta(seconds = sec)))

0:53:05.156403

In [61]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9435474961728454